---
title: "GraceLi_A2"
author: Grace Li
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F)
```

```{r}
library(tidyverse)
library(sf)
library(tigris)
library(censusapi)
library(mapview)
library(leaflet)

library(devtools)
install_github('walkerke/tigris')
library(tigris)
```


```{r}
Sys.setenv(CENSUS_KEY="9136d9427440997e3a0e797bbf837fa633066a90")

dec_vars_2020 <-
  listCensusMetadata(
    name = "2020/dec/pl",
    type = "variables"
  )

scc_pop_2020 <-
  getCensus(
    name = "dec/pl",
    vintage = 2020,
    region = "block:*", 
    regionin = "state:06+county:085",
    vars = "P1_001N"
  ) %>% 
  transmute(
    block =
      paste0(state,county,tract,block),
    pop = P1_001N
  )
```


```{r}
Sys.setenv(CENSUS_KEY="9136d9427440997e3a0e797bbf837fa633066a90")

dec_vars_2010 <-
  listCensusMetadata(
    name = "2010/dec/pl",
    type = "variables"
  )

scc_pop_2010 <-
  getCensus(
    name = "dec/pl",
    vintage = 2010,
    region = "block:*", 
    regionin = "state:06+county:085",
    vars = "P001001"
  ) %>% 
  transmute(
    block =
      paste0(state,county,tract,block),
    pop = P001001
  )
```


```{r}
scc_blocks_2020 <- blocks("CA", "Santa Clara", year = 2020, progress_bar = F)

pa_boundary <- places("CA", progress_bar = F) %>% 
  filter(NAME == "Palo Alto")

pa_pop_2020 <- scc_pop_2020 %>% 
  left_join(scc_blocks_2020 %>% select(block = GEOID20)) %>% 
  st_as_sf() %>% 
  st_centroid() %>% 
  .[pa_boundary, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(scc_blocks_2020 %>% select(block = GEOID20)) %>% 
  st_as_sf()

mapview(pa_pop_2020, zcol = "pop")
```


```{r}
scc_blocks_2010 <- blocks("CA", "Santa Clara", year = 2010, progress_bar = F)

pa_boundary <- places("CA", progress_bar = F) %>% 
  filter(NAME == "Palo Alto")

pa_pop_2010 <- scc_pop_2010 %>% 
  left_join(scc_blocks_2010 %>% select(block = GEOID10)) %>% 
  st_as_sf() %>% 
  st_centroid() %>% 
  .[pa_boundary, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(scc_blocks_2010 %>% select(block = GEOID10)) %>% 
  st_as_sf()

mapview(pa_pop_2010, zcol = "pop")
```


```{r}
pa_pop_final <-
  pa_pop_2010 %>% 
  st_transform(26910) %>% 
  mutate(
    original_area = st_area(.),
    #pop = (pa_pop_2020$pop) - (pa_pop_2010$pop)
  ) %>% 
  st_intersection(
    pa_pop_2020 %>% 
      st_transform(26910)
  ) %>% 
  mutate(
    leftover_area = st_area(.),
    perc_area = leftover_area / original_area,
    pop = pop * perc_area
  )

```


```{r}
leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(
    data = pa_pop_2020,
    stroke = F,
    fillOpacity = 0.5
  ) %>% 
  addPolygons(
    data = pa_pop_2010,
    color = "red",
    weight = 0.75,
    fill = F
  )
```


```{r}

```


