---
title: "Grace Li_A6"
author: Grace Li
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

```{r}
library(censusapi)
library(tidyverse)
library(tigris)
library(sf)
library(leaflet)
library(mapview)

Sys.setenv(CENSUS_KEY="9136d9427440997e3a0e797bbf837fa633066a90")
```

```{r}
pums_2019_1yr <- getCensus(
  name = "acs/acs1/pums",
  vintage = 2019,
  region = "public use microdata area:*", 
  regionin = "state:06",
  vars = c(
    "SERIALNO",
    "SPORDER",
    "PWGTP",
    "WGTP",
    "NP",
    "HINCP",
    "MV",
    "TEN",
    "YBL",
    "BLD",
    "AGEP"
  )
)

saveRDS(pums_2019_1yr, "a6_pums.rds")
pums_2019_1yr <- readRDS("a6_pums.rds")
```

```{r}
ca_pumas <-
  pumas("CA", cb = T, progress_bar = F)

sf_boundary <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME == "San Francisco")

sf_pumas <-
  ca_pumas %>% 
  st_centroid() %>% 
  .[sf_boundary, ] %>% 
  st_drop_geometry() %>% 
  left_join(ca_pumas %>% select(GEOID10)) %>% 
  st_as_sf()

mapview(sf_pumas)

sf_pums <-
  pums_2019_1yr %>% 
  mutate(
    PUMA = str_pad(public_use_microdata_area,5,"left","0")
  ) %>% 
  filter(PUMA %in% sf_pumas$PUMACE10)
```

```{r}
sf_pums_clean <- sf_pums %>%
  mutate(
    YBL = as.numeric(YBL),
    AGEP = as.numeric(AGEP),
    HINCP = as.numeric(HINCP)
  ) %>% 
  filter(YBL %in% 1:3) %>% 
  arrange(AGEP) %>% 
  group_by(SERIALNO) %>%
  summarize_all(first) %>%
  mutate(
    leadrisk = ifelse(
      (AGEP < 6) &
        (HINCP < 90000),
      1,
      0
    )
  ) 
```

```{r}
sf_pums_factor <- sf_pums_clean %>% 
  mutate(
    BLD = as.factor(BLD),
    PUMA = as.factor(PUMA),
    TEN = as.factor(TEN),
    MV = as.factor(MV)
  ) 
```

```{r}
logit_model <- glm(
  leadrisk ~ BLD + TEN + MV + PUMA,
  family = quasibinomial(),
  data = sf_pums_factor
)

summary(logit_model)
```

```{r}
predict(logit_model, sample_n(sf_pums_factor, 1), type = "response")
```











